# Site settings
title: Ram Bharadwaj
email: 
description: "cached thoughts"
baseurl: ""
url: "http://rokosbasilisk.github.io"
github_username:  rokosbasilisk

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
