# Site settings
title: Full Wrong
#email: 
#description: "Highly opinionated experimental results"
baseurl: ""
url: "http://rokosbasilisk.github.io"
github_username:  rokosbasilisk

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
